### ISSUE TITLE
Limit to subfolder

### ISSUE THREAD

**Issue by shift2design** [sjelfull/Craft-TemplateSelect#1]
Hi, this works great, thank you. One request is that I would like to restrict the user to a specific subfolder within the templates directory (instead of the root templates folder). I am new to craft from EE so I am stumbling trying to accomplish this but it seems like it should be fairly easy.

**Comment by sjelfull** [comment]
@shift2design Sorry for not checking on here before now, I've been travelling a lot. I'll add a configuration option, so you set where it will look for the templates, relative to your site template path.

**Comment by shift2design** [comment]
That would be great. I was able to set it so when you select in (when editing entry) it shows a specific folder but was unable to figure out how to output it correct. I've gotta get more familiar with Craft. Thank you for the response.

**Comment by sjelfull** [comment]
I've added the config setting **templateselectSubfolder** now, so you can set it to a subfolder of the site templates path.

Example: if you set it to **magnificentsubfolder**, it will be saved as magnificentsubfolder/templatename.html
