### ISSUE TITLE
Update to  Craft CMS 2.6.2950 path problem

### ISSUE THREAD

**Issue by ipetrov87** [sjelfull/Craft-TemplateSelect#5]
Hi!

Since i update to latest Craft CMS 2.6.2950 I get a wrong template path from Template selector field. I put all my templates in **templates** folder. I get this path from field **templatesD:/workspace/Craft/concept/craft/templates/templates/black.twig** instead **D:/workspace/Craft/concept/craft/templates/templates/black.twig**

**Comment by ipetrov87** [comment]
I think i find the problem. But have no idea how to fix it. 
In file **TemplateSelect_SelectFieldType.php** line 19 

`$templatesPath = $siteTemplatesPath = craft()->path->getSiteTemplatesPath();`

return **D:\workspace\Craft\aeraconcept\craft\templates\templates**

and line 47 

`$filename = str_replace(realpath($templatesPath), '', $filename);`

the function `realpath($templatesPath)` return **D:/workspace/Craft/aeraconcept/craft/templates/templates/black.twig**

The problem is tha in one place path is returned with **\** and on the other is with **/**

**Comment by sjelfull** [comment]
Thanks for reporting this. I'm current quite busy, so unsure if I have time to get a fix done for this this/next week. I also don't run Windows, so I might not be able to test any solutions.

One thing: According to the docs, `realpath()` is supposed to return the correct directory separator on windows.

Are you sure that's where it get changed?
